export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_SECTOR_BEGIN = 'CREATE_SECTOR_BEGIN'
export const CREATE_SECTOR_SUCCESS = 'CREATE_SECTOR_SUCCESS'
export const CREATE_SECTOR_ERROR = 'CREATE_SECTOR_ERROR'

export const GET_SECTORS_BEGIN = 'GET_SECTORS_BEGIN'
export const GET_SECTORS_SUCCESS = 'GET_SECTORS_SUCCESS'

export const SET_EDIT_SECTOR = 'SET_EDIT_SECTOR'

export const DELETE_SECTOR_BEGIN = 'DELETE_SECTOR_BEGIN'

export const EDIT_SECTOR_BEGIN = 'EDIT_SECTOR_BEGIN'
export const EDIT_SECTOR_SUCCESS = 'EDIT_SECTOR_SUCCESS'
export const EDIT_SECTOR_ERROR = 'EDIT_SECTOR_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
